apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-revip
  namespace: revip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revip
  template:
    metadata:
      labels:
        app: revip
    spec:
      containers:
      - name: revip
        image: pk219/revip:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ipserv-serv
  namespace: revip
spec:
  selector:
    app: revip
  ports:
  - name: revip
    protocol: TCP
    port: 80
    targetPort: 8000
