name: build-app
on:
  push:
    branches:
    - main
env:
  EKS_CLUSTER_NAME: revip-cluster
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Docker username
      run: echo ${{ secrets.DOCKER_USERNAME }}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build --no-cache -t pk219/revip .

    - name: Push Docker image to Docker Hub
      run: docker push pk219/revip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      run: kubectl rollout restart deployment/depl-revip -n revip
