name: build-app
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Docker username
      run: echo ${{ secrets.DOCKER_USERNAME }}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build --no-cache -t pk219/revip .

    - name: Push Docker image to Docker Hub
      run: docker push pk219/revip
